var citazioni =
	[
		"Questa non è skill, è un &hearts;&hearts;&hearts;&hearts;&hearts; &hearts;&hearts;&hearts;",
		"Basta rallentare internet con i porno!",
        "Viva STIM!",
		"Ma la mela... ha la barba?",
		"Igor è il migliore a Dota.",
		"<a href=\"https://dl.dropboxusercontent.com/u/23313381/apeggia.mp3\">Cosa fa un'ape su una foglia? Apeggia!</a>",
		"Il tappeto ha i <b>PELETTI</b>!",
		"<a href=\"https://dl.dropboxusercontent.com/u/23313381/seeeee.mp3\">Seeee seeee seeeeeeeeeeeeeeeeeee</a>",
		"Quel tipo <b>NON MUORE</b>!",
		"<b>FAI SCENDERE QUESTA NAVE</b>!",
		"Questo sito usa AIMBOT.",
		"Sensei<small class=\"putin\">sei<small class=\"putin\">sei</small></small>",
		"Igor è ora Senza Codino.",
		"Ste! Ste! I GLITCH!",
		"Ste, prendi gli orologi, non i braccialetti!",
		"Ah non lo so io!",
		"Questo è bello!",
		"Beh sì, capolavoro!",
		"Nel <b>MAREEEEEE</b>",
		"Ma che oh!",
		"Alè AIMBOT WALLHACK!",
		"WhaaaaAAAAAAAA<b>AAAAAAA</b>AAAAAAAaaaat",
		"<a href=\"https://www.youtube.com/watch?v=WUhOnX8qt3I\">Do you believe in magic?</a>",
		"Ma è bellissimo!",
		"Furbuffissimo!",
		"Capitan Balu!",
        "Basta, io qui <b>cambio gilda</b>!",
        "Non paga mai nessuno l'affitto!",
        "Grafica: c'è. Troppa acqua. 9/10 IGN",
		"Heroes of the Storm: Come Skyrim, con i cavalli. 9/11 IGN",
        "Il tuo PC è pieno di virus cinesi!",
        "<img src=\"https://static-cdn.jtvnw.net/emoticons/v1/25/1.0\"></img>",
        "<img src=\"http://static-cdn.jtvnw.net/emoticons/v1/1902/1.0\"></img>",
        "ORA VA SKYRIM SUL MIO PC!",
        "Zuppa",
        "Frank è una banana.",
        "Max è uno shoppone!",
        "C'è del pepe!",
        "0 in gioco, 0 online, 5 in chat",
        "Coming soon at a PC near you.",
        "Voi volete fare solo <b>big money</b>",
        "Moneygrabber",
        "<a href=\"http://pastebin.com/raw.php?i=7nKgG10c\">Vendere sul mercato è come pagare le tasse!</a>",
        "FSHHHCRRRCHFSSSSSSSSSS",
        "Hai vinto la Fascia del Maestro!",
        "Hai vinto la Medaglia del Gran Maestro!",
        "Hai vinto il Medaglione del Maestro Supremo!",
        "Hai vinto un Medaglione di Pollo!",
        "Frank happens.",
		"Frank being Frank",
		"Allah VACBAAAAN",
        "Muscatello plis",
        "La password non é admin!",
        "VAC BANNED",
        "Ehiiii, Argento Dueeee",
		"Ehiiii, Argento Treeee",
        "Spari sì o no?",
		"Tranquilli, sono <a href=\"https://dl.dropboxusercontent.com/u/23313381/CSGORanks/L\'Elite%20Globale.png\">deboli</a>",
        "Chorus of Icarus Online",
        "Mumble o Steam?",
        "Votchic",
        "Votkik",
        "Votekick",
        "Consiglio #206",
		"Perchè fanno server London e non server Piumazzo?!",
		"Non è Wallhack! E' di più! Di più!",
		"Sono finalmente usciti i server Piumazzo su Dota!",
		"*rumore di ventilatore*",
		"QUEL VENTILATORE!!!",
		"Overthrow o Dota Imba?",
		"Ho la Z appiccicosa",
		"Il messaggio passa",
		"Ho i braccialetti nella mano destra",
		"La scrivania è sudata",
		"Ho 300pp!",
		"Vuoi morire?!",
		"Hai un coltello, vendilo!",
		"E' un coltello da 50 €, non da 30 €!"
	];
	
var numero = Math.floor(Math.random() * citazioni.length);

$("#citazioni").html(citazioni[numero]);